### ISSUE TITLE
T: Improve text legibility

### ISSUE THREAD

**Issue by ysaliens** [TeraInferno/CSCI5828-RemotelyPossible#52]
Blue text on Blue background in some application/project sections is not easily readable.

**Comment by bshouse** [comment]
Be sure you have the latest code from GitHub. I noticed the same thing and changed the color scheme (to sunshine). Check out http://jqueryui.com/themeroller/ for the Gallery of pre-configured color schemes. If you have an eye for color, you could do a "Roll your own" theme to match school colors...
